# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/alek/clion-2019.1.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/alek/clion-2019.1.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alek/Documents/LimbicEngine_OpenGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alek/Documents/LimbicEngine_OpenGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/alek/clion-2019.1.4/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/alek/clion-2019.1.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alek/Documents/LimbicEngine_OpenGL/CMakeFiles /home/alek/Documents/LimbicEngine_OpenGL/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alek/Documents/LimbicEngine_OpenGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LimbicEngine

# Build rule for target.
LimbicEngine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LimbicEngine
.PHONY : LimbicEngine

# fast build rule for target.
LimbicEngine/fast:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/build
.PHONY : LimbicEngine/fast

LimbicEngine/contentLoader.o: LimbicEngine/contentLoader.cpp.o

.PHONY : LimbicEngine/contentLoader.o

# target to build an object file
LimbicEngine/contentLoader.cpp.o:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/contentLoader.cpp.o
.PHONY : LimbicEngine/contentLoader.cpp.o

LimbicEngine/contentLoader.i: LimbicEngine/contentLoader.cpp.i

.PHONY : LimbicEngine/contentLoader.i

# target to preprocess a source file
LimbicEngine/contentLoader.cpp.i:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/contentLoader.cpp.i
.PHONY : LimbicEngine/contentLoader.cpp.i

LimbicEngine/contentLoader.s: LimbicEngine/contentLoader.cpp.s

.PHONY : LimbicEngine/contentLoader.s

# target to generate assembly for a file
LimbicEngine/contentLoader.cpp.s:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/contentLoader.cpp.s
.PHONY : LimbicEngine/contentLoader.cpp.s

LimbicEngine/io.o: LimbicEngine/io.cpp.o

.PHONY : LimbicEngine/io.o

# target to build an object file
LimbicEngine/io.cpp.o:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/io.cpp.o
.PHONY : LimbicEngine/io.cpp.o

LimbicEngine/io.i: LimbicEngine/io.cpp.i

.PHONY : LimbicEngine/io.i

# target to preprocess a source file
LimbicEngine/io.cpp.i:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/io.cpp.i
.PHONY : LimbicEngine/io.cpp.i

LimbicEngine/io.s: LimbicEngine/io.cpp.s

.PHONY : LimbicEngine/io.s

# target to generate assembly for a file
LimbicEngine/io.cpp.s:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/io.cpp.s
.PHONY : LimbicEngine/io.cpp.s

LimbicEngine/main.o: LimbicEngine/main.cpp.o

.PHONY : LimbicEngine/main.o

# target to build an object file
LimbicEngine/main.cpp.o:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/main.cpp.o
.PHONY : LimbicEngine/main.cpp.o

LimbicEngine/main.i: LimbicEngine/main.cpp.i

.PHONY : LimbicEngine/main.i

# target to preprocess a source file
LimbicEngine/main.cpp.i:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/main.cpp.i
.PHONY : LimbicEngine/main.cpp.i

LimbicEngine/main.s: LimbicEngine/main.cpp.s

.PHONY : LimbicEngine/main.s

# target to generate assembly for a file
LimbicEngine/main.cpp.s:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/main.cpp.s
.PHONY : LimbicEngine/main.cpp.s

LimbicEngine/map.o: LimbicEngine/map.cpp.o

.PHONY : LimbicEngine/map.o

# target to build an object file
LimbicEngine/map.cpp.o:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/map.cpp.o
.PHONY : LimbicEngine/map.cpp.o

LimbicEngine/map.i: LimbicEngine/map.cpp.i

.PHONY : LimbicEngine/map.i

# target to preprocess a source file
LimbicEngine/map.cpp.i:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/map.cpp.i
.PHONY : LimbicEngine/map.cpp.i

LimbicEngine/map.s: LimbicEngine/map.cpp.s

.PHONY : LimbicEngine/map.s

# target to generate assembly for a file
LimbicEngine/map.cpp.s:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/map.cpp.s
.PHONY : LimbicEngine/map.cpp.s

LimbicEngine/pc_gl_render.o: LimbicEngine/pc_gl_render.cpp.o

.PHONY : LimbicEngine/pc_gl_render.o

# target to build an object file
LimbicEngine/pc_gl_render.cpp.o:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/pc_gl_render.cpp.o
.PHONY : LimbicEngine/pc_gl_render.cpp.o

LimbicEngine/pc_gl_render.i: LimbicEngine/pc_gl_render.cpp.i

.PHONY : LimbicEngine/pc_gl_render.i

# target to preprocess a source file
LimbicEngine/pc_gl_render.cpp.i:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/pc_gl_render.cpp.i
.PHONY : LimbicEngine/pc_gl_render.cpp.i

LimbicEngine/pc_gl_render.s: LimbicEngine/pc_gl_render.cpp.s

.PHONY : LimbicEngine/pc_gl_render.s

# target to generate assembly for a file
LimbicEngine/pc_gl_render.cpp.s:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/pc_gl_render.cpp.s
.PHONY : LimbicEngine/pc_gl_render.cpp.s

LimbicEngine/player.o: LimbicEngine/player.cpp.o

.PHONY : LimbicEngine/player.o

# target to build an object file
LimbicEngine/player.cpp.o:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/player.cpp.o
.PHONY : LimbicEngine/player.cpp.o

LimbicEngine/player.i: LimbicEngine/player.cpp.i

.PHONY : LimbicEngine/player.i

# target to preprocess a source file
LimbicEngine/player.cpp.i:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/player.cpp.i
.PHONY : LimbicEngine/player.cpp.i

LimbicEngine/player.s: LimbicEngine/player.cpp.s

.PHONY : LimbicEngine/player.s

# target to generate assembly for a file
LimbicEngine/player.cpp.s:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/player.cpp.s
.PHONY : LimbicEngine/player.cpp.s

LimbicEngine/render.o: LimbicEngine/render.cpp.o

.PHONY : LimbicEngine/render.o

# target to build an object file
LimbicEngine/render.cpp.o:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/render.cpp.o
.PHONY : LimbicEngine/render.cpp.o

LimbicEngine/render.i: LimbicEngine/render.cpp.i

.PHONY : LimbicEngine/render.i

# target to preprocess a source file
LimbicEngine/render.cpp.i:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/render.cpp.i
.PHONY : LimbicEngine/render.cpp.i

LimbicEngine/render.s: LimbicEngine/render.cpp.s

.PHONY : LimbicEngine/render.s

# target to generate assembly for a file
LimbicEngine/render.cpp.s:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/render.cpp.s
.PHONY : LimbicEngine/render.cpp.s

LimbicEngine/shaderLoader.o: LimbicEngine/shaderLoader.cpp.o

.PHONY : LimbicEngine/shaderLoader.o

# target to build an object file
LimbicEngine/shaderLoader.cpp.o:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/shaderLoader.cpp.o
.PHONY : LimbicEngine/shaderLoader.cpp.o

LimbicEngine/shaderLoader.i: LimbicEngine/shaderLoader.cpp.i

.PHONY : LimbicEngine/shaderLoader.i

# target to preprocess a source file
LimbicEngine/shaderLoader.cpp.i:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/shaderLoader.cpp.i
.PHONY : LimbicEngine/shaderLoader.cpp.i

LimbicEngine/shaderLoader.s: LimbicEngine/shaderLoader.cpp.s

.PHONY : LimbicEngine/shaderLoader.s

# target to generate assembly for a file
LimbicEngine/shaderLoader.cpp.s:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/shaderLoader.cpp.s
.PHONY : LimbicEngine/shaderLoader.cpp.s

LimbicEngine/textureLoader.o: LimbicEngine/textureLoader.cpp.o

.PHONY : LimbicEngine/textureLoader.o

# target to build an object file
LimbicEngine/textureLoader.cpp.o:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/textureLoader.cpp.o
.PHONY : LimbicEngine/textureLoader.cpp.o

LimbicEngine/textureLoader.i: LimbicEngine/textureLoader.cpp.i

.PHONY : LimbicEngine/textureLoader.i

# target to preprocess a source file
LimbicEngine/textureLoader.cpp.i:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/textureLoader.cpp.i
.PHONY : LimbicEngine/textureLoader.cpp.i

LimbicEngine/textureLoader.s: LimbicEngine/textureLoader.cpp.s

.PHONY : LimbicEngine/textureLoader.s

# target to generate assembly for a file
LimbicEngine/textureLoader.cpp.s:
	$(MAKE) -f CMakeFiles/LimbicEngine.dir/build.make CMakeFiles/LimbicEngine.dir/LimbicEngine/textureLoader.cpp.s
.PHONY : LimbicEngine/textureLoader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... LimbicEngine"
	@echo "... edit_cache"
	@echo "... LimbicEngine/contentLoader.o"
	@echo "... LimbicEngine/contentLoader.i"
	@echo "... LimbicEngine/contentLoader.s"
	@echo "... LimbicEngine/io.o"
	@echo "... LimbicEngine/io.i"
	@echo "... LimbicEngine/io.s"
	@echo "... LimbicEngine/main.o"
	@echo "... LimbicEngine/main.i"
	@echo "... LimbicEngine/main.s"
	@echo "... LimbicEngine/map.o"
	@echo "... LimbicEngine/map.i"
	@echo "... LimbicEngine/map.s"
	@echo "... LimbicEngine/pc_gl_render.o"
	@echo "... LimbicEngine/pc_gl_render.i"
	@echo "... LimbicEngine/pc_gl_render.s"
	@echo "... LimbicEngine/player.o"
	@echo "... LimbicEngine/player.i"
	@echo "... LimbicEngine/player.s"
	@echo "... LimbicEngine/render.o"
	@echo "... LimbicEngine/render.i"
	@echo "... LimbicEngine/render.s"
	@echo "... LimbicEngine/shaderLoader.o"
	@echo "... LimbicEngine/shaderLoader.i"
	@echo "... LimbicEngine/shaderLoader.s"
	@echo "... LimbicEngine/textureLoader.o"
	@echo "... LimbicEngine/textureLoader.i"
	@echo "... LimbicEngine/textureLoader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

